WeatherApp/Models/CityModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherApp.Models
{
    public class CityModel
    {
        [Required]
        [MaxLength(50),MinLength(3)]
        public string City { get; set; }
    }
}

WeatherApp/Models/Clouds.cs
namespace WeatherApp.Models
{
    public class Clouds
    {
        public int all { get; set; }
    }   
}

WeatherApp/Models/Coord.cs
namespace WeatherApp.Models
{
    public class Coord
    {
        public float Lon { get; set; }
        public float Lat { get; set; }
       
    }
}

WeatherApp/Models/ErrorViewModel.cs
using System;

namespace WeatherApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherApp/Models/GetWeather.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherApp.Models
{
    public class GetWeather
    {
        [Display(Name="City Name")]
        public string Name { get; set; }
        public float Temperature { get; set; }
        public int Humditiy { get; set; }
        public int Pressure { get; set; }
        public float Wind { get; set; }
        [Display(Name ="Weather Condition")]
        public string Weather { get; set; }
        public int TimeZone { get; set; }
        public string Country { get; set; }
        public float feelsLike { get; set; }
        public float min { get; set; }
        public float max { get; set; }
        public string message { get; set; }
    }
}

WeatherApp/Models/Main.cs
namespace WeatherApp.Models
{
    public class Main
    {
        public float temp { get; set; } 
        public float feels_like { get; set; }
        public float temp_min { get; set; }
        public float temp_max { get; set; }
        public int pressure { get; set; }
        public int humidity { get; set; }
        
    }
}

WeatherApp/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeatherApp.Models
{
    public class Result
    {
        public Coord Coord { get; set; }
        public List<Weather> Weather { get; set; }
        public string Base { get; set; }
        public Main main { get; set; }
        public int Visibility { get; set; }
        public Wind Wind { get; set; }
        public Clouds Clouds { get; set; }
        public int dt { get; set; }
        public Sys Sys { get; set; }
        public int TimeZone { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int cod { get; set; }
    }
}

WeatherApp/Models/Sys.cs
namespace WeatherApp.Models
{
    public class Sys
    {
        public int type { get; set; }
        public int id { get; set; }
        public string country { get; set; }
        public int sunrise { get; set; }
        public int sunset { get; set; }

      
    }
}

WeatherApp/Models/Weather.cs
namespace WeatherApp.Models
{
    public class Weather
    {
        public int id { get; set; }
        public string main { get; set; }
        public string description  { get; set; }
        public string icon { get; set; }

    }
}

WeatherApp/Models/Wind.cs
namespace WeatherApp.Models
{
    public class Wind
    {
        public float speed { get; set; }
        public int deg { get; set; }
       
    }
}

WeatherApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WeatherApp.Models;

namespace WeatherApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WeatherApp/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WeatherApp.Models;
using WeatherApp.Services;

namespace WeatherApp.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IwReprosetory _Weather;
        public WeatherController(IwReprosetory Weather)
        {
            _Weather = Weather;
        }
        public object Modelstate { get; private set; }

        public IActionResult City()
        {
            return View();
        }
        [HttpPost]
        public IActionResult City(CityModel cityModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("GetWeather",new{city=cityModel.City});
            }
            return View(cityModel);
        }

        public IActionResult GetWeather(string city)
        {
            Result res = _Weather.GetForcast(city);
            GetWeather get = new GetWeather();
            if (res != null)
            {
                get.Name = res.name;
                get.Temperature = res.main.temp;
                get.Pressure = res.main.pressure;
                get.Humditiy = res.main.humidity;
                get.Wind = res.Wind.speed;
                get.Weather = res.Weather[0].main;
                get.TimeZone = res.TimeZone;
                get.Country = res.Sys.country;
                get.max = res.main.temp_max;
                get.min = res.main.temp_min;
                get.feelsLike = res.main.feels_like;

            }
            else get.message = "Wrong City Name";
            return View(get);
        }



    }
}

WeatherApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WeatherApp/Views/Shared/_Layout.cshtml
@model WeatherApp.Models.GetWeather
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
  
<body style=" 
    background-image:url('../helpers/rainy.jpg');
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;">
    <header style="background-color:black;color:white">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Weather" asp-action="City">Weather App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>

    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:#343a40;color:white">
        <div class="container">
            &copy; 2022 - WeatherApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherApp/Views/Weather/City.cshtml
@model WeatherApp.Models.CityModel

<div class="container">

    <form method="post" asp-action="City">
        <div class="container m-2" style="position:fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);">

            <input asp-for="City" type="text" class="form-control" placeholder="Enter Your City......" style="text-align:center">
            <span asp-validation-for="City" class="bg-danger" style="color:wheat"></span>
            <div class="d-flex justify-content-center m-2">
                <input type="submit" class="btn btn-primary" value="Search" style="width:120px;font-weight:600" />
            </div>
        </div>
    </form>
</div>
@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
  }
 }

WeatherApp/Views/Weather/GetWeather.cshtml
@model WeatherApp.Models.GetWeather

@{
    ViewData["Title"] = "GetWeather";
}

<div class="row com" style="@(Model.Weather=="Clear"?"background-image:url('../helpers/tree.jpg');color:black":"background-image:url('../helpers/cloud.jpg');color:White")";
       background-position: center;
       background-repeat: no-repeat;
       background-size: cover;color:white">   
   
    <div class="col-8" style="margin-top:20px">
        @if (Model.message == null)
        {
            <table style="height:400px;margin-left:80px ">
                <tbody>
                    <tr>
                        <td>
                            <h4>@DateTime.Now.ToString("dddd") </h4>
                            <h4>@DateTime.Now.ToString("dd MMMM yyyy") </h4>
                        </td>


                    </tr>
                    <tr>
                        <td>
                            <h2 style="font-size:40px">@Model.Weather</h2>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div style="font-size:100px;">@((int)Model.Temperature) °C </div>
                            <span style="font-size:20px">Feels Like @((int)Model.feelsLike) °C</span>

                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span style="font-size:20px">@Model.Name ,@Model.Country</span>
                        </td>

                    </tr>
                    
                    <tr style="margin-top:20px;">
                        <td>
                            <a asp-action="City" class="btn btn-warning">Back to Search</a>
                        </td>
                            </tr>

                        </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-danger" style="text-align:center">@Model.message</div>
            <a asp-action="City" class="btn btn-outline-warning">Back to List</a>
        }



        <div>



        </div>
    </div>
    <div class="col-4" >
    
        <div class="card text-white bg-secondary mb-2 m-4" style="max-width: 10rem;">
            <div class="card-header" style="text-align:center"><h5>Humditiy</h5></div>
            <div class="card-body">
                <h5 class="card-title" style="text-align:center">@Model.Humditiy %</h5>
            </div>
        </div>

        <div class="card text-white bg-secondary mb-2 m-4" style="max-width: 10rem;">
            <div class="card-header" style="text-align:center"><h5>Pressure</h5></div>
            <div class="card-body">
                <h5 class="card-title" style="text-align:center">@Model.Pressure mbar</h5>
            </div>
        </div>

        <div class="card text-white bg-secondary mb-2 m-4" style="max-width: 10rem;">
            <div class="card-header" style="text-align:center"><h5>Wind Speed</h5></div>
            <div class="card-body">
                <h5 class="card-title" style="text-align:center">@(((int)(Model.Wind/0.277778))) Km/h</h5>
            </div>
        </div>
        
        </div>
    </div>
 